### ISSUE TITLE
Mouse Up/Down MacOS issue

### ISSUE THREAD

**Issue by g8kig** [tekknolagi/full-beans#1]
Original did not work for me.
This fixes it
```

diff --git a/fenster.h b/fenster.h
index 44ebc4a..a30931f 100644
--- a/fenster.h
+++ b/fenster.h
@@ -163,10 +163,8 @@ FENSTER_API int fenster_loop(struct fenster *f) {
   NSUInteger evtype = msg(NSUInteger, ev, "type");
   switch (evtype) {
   case 1: /* NSEventTypeMouseDown */
-    f->mouse |= 1;
-    break;
   case 2: /* NSEventTypeMouseUp*/
-    f->mouse &= ~1;
+    f->mouse = (evtype == 1);
     break;

```
Not sure if this is right or not.

**Comment by tekknolagi** [comment]
Oh I think it's actually the way we treat the mouse on our end, not fenster

Don't have a Mac so can't test but I'll try sending you a patch and if it fixes it on your end, want to make a PR?

**Comment by tekknolagi** [comment]
@g8kig / @amitv87 does 6ecfddd7c6aa38531a08a84f458bfba83c7a9c72 fix it for you?

**Comment by g8kig** [comment]
Confirmed . Fixed for me.

**Comment by tekknolagi** [comment]
(Ended up just making it into a PR and thanking you in the message)
